### PR TITLE
Bug/double opt in triggered despite being disabled in settings

### LINKED ISSUE #113: Double Opt-In triggered despite being disabled in settings
### Describe the bug

The plugin is triggering the double opt-in process regardless of the opt-in setting configured in the plugin. Even when "Use Double Opt-In" is unchecked and the settings are saved, the plugin displays a double opt-in confirmation message after form submission and sends the double opt-in email to the subscriber.

**Observed Behavior:**
- After submitting the form, the plugin displays the double opt-in confirmation message.
- The subscriber receives a double opt-in email, even though the setting is disabled.

**Expected Behavior:**
- When "Use Double Opt-In" is disabled, subscribers should be added directly to the mailing list without a confirmation email.

**Additional Context:**
- Testing was performed in a sandbox WordPress account.
- Both the confirmation message and the double opt-in email were observed despite the setting being explicitly disabled.

### Steps to Reproduce

1. Install and configure the List Subscribe plugin for WordPress.  
   - [[Installation instructions](https://mailchimp.com/help/connect-or-disconnect-list-subscribe-for-wordpress/)](https://mailchimp.com/help/connect-or-disconnect-list-subscribe-for-wordpress/)  
2. Navigate to the plugin settings and uncheck "Use Double Opt-In."  
3. Save the settings.  
4. Use the subscription form on the front-end of the website to sign up for the mailing list.  

### Screenshots, screen recording, code snippet

1. **Double Opt-In Setting Disabled**

listsub_doi_disabled

2. **Form Submission with Double Opt-In Triggered**

listsub_doi_used

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #114: Existing subscriber can sign up even if "Update Existing Subscriber?" is turned off
### Describe the bug

An existing subscriber can sign up with the same email and not receive the expected "This email address is already subscribed to the list."

Introduced with `==` loose equality to `===` strict equality change.

### Steps to Reproduce

1. Turn off "Update Existing Subscriber?"
2. Sign up with an email address
3. Use the same email address to sign up again
4. The submission will succeed where it should have failed

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/2ff3880a-cbed-43a7-a00a-32b0a67e7440

subscriber-exist-successful-signup

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MaxwellGarceau**
### Description of the Change

This PR bundles a two related issues.

- [Double Opt-In triggered despite being disabled in settings:](https://github.com/mailchimp/wordpress/issues/113) Fixes a bug causing double opt-in to occur every time regardless of Mailchimp WP settings on new user sign ups
- [Existing subscriber can sign up even if "Update Existing Subscriber?" is turned off:](https://github.com/mailchimp/wordpress/issues/114) Fixed a bug that caused the "Update Existing Subscriber?" setting to essentially always return as true. This caused the FE Mailchimp WP form to always return a success when subscribers would sign up with the same email.

Closes #113
Closes #114 

#### Double Opt-In triggered despite being disabled in settings
https://github.com/user-attachments/assets/c5f8d2d5-2cb9-448b-88f1-05867df832ec

1. Ensure that Double Opt-In is disabled in the Mailchimp WP settings page
2. Navigate to the FE and submit a new form submission with an email address you control (e.g. max.garceau+newsubmission@10up.com)
3. Check your email and ensure that you haven't received an email
4. Check your Mailchimp account to ensure the contact has been created

##### If Double Opt-In is enabled and a `pending` user tries to update their information, then their status will still be `pending` and they will have to confirm the original confirmation email (bug fix/logic change)
Previously, the conditional check was attempting to skip Double Opt-in for any emails with an existing status.

https://github.com/user-attachments/assets/0a49070a-afe1-482b-ac71-ba2e95fb9bac

1. Turn on Double Opt-In in the Mailchimp WP settings
2. Turn on "Update Existing Subscribers?" in the Mailchimp WP settings
3. Sign up with a new subscriber
4. DO NOT CONFIRM THE EMAIL
5. Check your Mailchimp account to confirm that the contact has not been created
6. Sign up and change some information with that same email
7. You WILL NOT receive another confirmation email. Confirm the original confirmation email.
8. Verify that the new contact is created in the Mailchimp account with the changes you've entered

#### Fix: Existing subscriber could sign up even if "Update Existing Subscriber?" is turned off

https://github.com/user-attachments/assets/8bbf31f2-a6cb-429c-b918-2cf99a49aea7

1. Turn "Update Existing Subscriber?" off in the Mailchimp WP settings
9. Sign up with a new subscriber on the FE submission form
10. Sign up a second time
11. You should receive an error stating "This email address has already been subscribed to this list"

##### If "Update Existing Subscriber?" is disabled and the email does not belong to a new subscriber then don't let them sign up (changed logic)
Previously, the conditional check would only check for `subscribed` emails to throw an error. Now, any existing email type will throw the error.

https://github.com/user-attachments/assets/b03403ed-8c40-4bf7-83b9-cd32abbdc83d

1. Turn "Update Existing Subscriber?" off in the Mailchimp WP settings
2. `subscribed` - Sign up with an already subscribed email on the FE submission form. You should see "This email address has already been subscribed to this list."
3. `unsubscribed` - Sign up with an email that has been unsubscribed from this list. You should see "This email address has already been subscribed to this list."
4. Enable Double Opt-In
12. Sign up with a new email
13. DO NOT CONFIRM THE EMAIL
14. `pending` - Try signing up again with the email. You should see "This email address has already been subscribed to this list."

Other statuses include `cleaned`, `transactional`, and `archived`, but I don't think we need to worry about testing those.

### Changelog Entry

> Fixed - Bug causing all new subscribers to receive a double opt-in email.
> Fixed - Bug causing contacts with any Mailchimp status (subscribed, unsubscribed, pending, etc.) to be able to submit the sign-up form even if "Update Existing Subscriber?" was disabled.
> Fixed - Pending contacts will now still be required to confirm their original confirmation email if they try to update their contact while "Update Existing Subscribers?" and "Double Opt-in" are both enabled.

### Credits

Props Nathan Tetzlaff, @MaxwellGarceau, [pluckvermont](https://profiles.wordpress.org/pluckvermont/).

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/mailchimp/wordpress/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: mailchimp.php [hunk 1]
```diff
@@ -904,9 +904,10 @@ function mailchimp_sf_signup_submit() {
 	$url    = 'lists/' . $list_id . '/members/' . md5( strtolower( $email ) );
 	$status = mailchimp_sf_check_status( $url );
 
-	// If update existing is turned off and the subscriber exists, error out.
-	if ( get_option( 'mc_update_existing' ) === false && 'subscribed' === $status ) {
-		$msg   = esc_html__( 'This email address is already subscribed to the list.', 'mailchimp' );
+	// If update existing is turned off and the subscriber is not new, error out.
+	$is_new_subscriber = false === $status;
+	if ( ! get_option( 'mc_update_existing' ) && ! $is_new_subscriber ) {
+		$msg   = esc_html__( 'This email address has already been subscribed to this list.', 'mailchimp' );
```
Comment (MaxwellGarceau) [inline mailchimp.php:910]: ‼️ ‼️ I changed the functionality slightly here according to my interpretation of the use case.

If "Update Existing Subscriber?" is disabled and the email does not belong to a new subscriber then don't let them sign up.

The previously functionality only checked for emails with a `subscribed` status. This missed `unsubscribed`, `pending`, and the other possible Mailchimp statuses.

‼️ **Question:** Do we want to update `unsubscribed` and `pending` users as well? If we don't update `unsubscribed` users then it will be functionally impossible for any user to resubscribe once unsubscribed. This directly relates to https://github.com/mailchimp/wordpress/issues/93.

File: mailchimp.php [hunk 2]
```diff
@@ -944,36 +945,37 @@ function mailchimp_sf_signup_submit() {
...
-		}
+	// Early return for already subscribed users
+	if ( 'subscribed' === $status ) {
+		return $body;
 	}
+
+	// Subscribe the user immediately unless double opt-in is enabled
+	// No need to check user $status because we're handling that before this point
+	$body->status = $double_optin ? 'pending' : 'subscribed';
+
```
Comment (MaxwellGarceau) [inline mailchimp.php:970]: I've removed the intended check for new subscribers. The only determinant for the status in the API request will be if double opt-in is set or not.

This makes sense to me because no Mailchimp user with any status (subscribed, unsubscribed, pending, etc) should make it to this point unless "Update Existing Subscriber?" is enabled.

In addition, if double opt-in is selected, it seems more likely to me that a user would want the confirmation email sent for new subscribers and existing updates.

‼️‼️ **Question:** It may be confusing for an existing subscriber to receive a confirmation email. **Should we prevent existing contacts from ever receiving a `pending` status?**

File: mailchimp.php [hunk 3]
```diff
@@ -944,36 +952,38 @@ function mailchimp_sf_signup_submit() {
...
+	// Early return for already subscribed users
+	if ( 'subscribed' === $status ) {
+		return $body;
 	}
+
+	// Subscribe the email immediately unless double opt-in is enabled
+	// "unsubscribed" and "subscribed" existing emails have been excluded at this stage
+	// "pending" emails should follow double opt-in rules
+	$body->status = $double_optin ? 'pending' : 'subscribed';
+
```
Comment (MaxwellGarceau) [inline mailchimp.php:978]: ‼️‼️ I've removed the intended check for new subscribers. The only determinant for the status in the API request will be if double opt-in is set or not.

This makes sense to me because no Mailchimp user with a status of `subscribed` or `unsubscribed` should make it to this point. `unsubscribed` users can not be resubscribed through the API and `subscribed` users have an early return.

`pending` users follow whatever logic the double opt-in is set to.

‼️‼️ Question: I checked the documentation and three additional statuses of `cleaned`, `archived`, and `transactional` exists. Do you think this is worth following up? I'd be happy to support these statuses as well.

**Comment by MaxwellGarceau** [comment]
Some of the logic around setting a subscribers status as well as what type of subscribers should be allowed to update their contact info in Mailchimp are a bit hard to remember. I think those would be good candidates for unit tests. What does everyone else think?

**Comment by dkotter** [comment]
> I think those would be good candidates for unit tests. What does everyone else think?

I'm fine with adding unit tests here

File: mailchimp.php (hunk 1 above)
Comment (dkotter) [reply mailchimp.php:910]: I do think we'll want to allow other statuses to work here besides just `subscribed`. As a user, I think I'd consider it a bug if someone that has unsubscribed can't resubscribe if that setting is on. The way I think this should work is if someone is subscribed or is in a pending state (I would assume that means they subscribed but haven't verified that yet), we shouldn't allow them to resubscribe if this option is enabled. But if they have never subscribed or if they have unsubscribed, they should be allowed to subscribe

File: mailchimp.php (hunk 3 above)
Comment (dkotter) [reply mailchimp.php:974]: I'm not sure what those statuses correspond to but if we haven't been looking at those before, I think we can probably ignore them for now and open a separate issue to investigate adding support for those

File: mailchimp.php (hunk 1 above)
Comment (MaxwellGarceau) [reply mailchimp.php:910]: > The way I think this should work is if someone is subscribed or is in a pending state, we shouldn't allow them to resubscribe if this option is enabled `mc_update_existing`

I 100% agree with you.
- In the case of `subscribed`, the sign up request will update the existing contact instead of creating a duplicate.
- In the case of `pending` (subscribed, but haven't verified), their information will also be updated. However, the user must still confirm the email before the contact is created. The exception to this is if single opt-in has been enabled then the `pending` contact will be created immediately without needing to verify the original email.

> [If `mc_update_existing` is enabled or disabled] But if they have never subscribed they should be allowed to subscribe
Yes! Current functionality.

> [If `mc_update_existing` is disabled] If they have unsubscribed they should be allowed to subscribe
I agree as well. The current Mailchimp functionality is that [contacts can not be resubscribed through the API](https://www.reddit.com/r/MailChimp/comments/z8ui4l/comment/iydekrz/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). However, there's a solution in #117 to still address this scenario.

File: mailchimp.php (hunk 3 above)
Comment (MaxwellGarceau) [reply mailchimp.php:974]: Sounds good! I'll open a new issue for those new statuses with a brief description of what they are.

Comment (MaxwellGarceau) [reply mailchimp.php:974]: New issue https://github.com/mailchimp/wordpress/issues/119 to address additional Mailchimp statuses of `cleaned`, `archived`, and `transactional`.

**Review by dkotter — APPROVED** [review]

**Comment by MaxwellGarceau** [comment]
Update on the unit tests. I've been prioritizing wrapping up other in progress tickets. The unit tests may not be ready before I move onto another project next week.

**Comment by qasumitbagthariya** [comment]
### QA Update  ✅ 

-------------

@MaxwellGarceau Thanks for the detailed comment and testing video.

I have verified this PR in the `bug/double-opt-in-triggered-despite-being-disabled-in-settings` branch which has been fixed and is functioning as intended.

I tested the following on this branch:

- Double Opt-In triggered despite being disabled in settings ✅

- If Double Opt-In is enabled and a pending user tries to update their information, then their status will still be pending and they will have to confirm the original confirmation email (bug fix/logic change) ✅

- Fix: Existing subscriber could sign up even if "Update Existing Subscriber?" is turned off  ✅

- If "Update Existing Subscriber?" is disabled and the email does not belong to a new subscriber then don't let them sign up (changed logic) ✅


**Testing Environment** 

<Details>

- WordPress: 6.7.1
- Theme: Twenty Twenty-Four 1.3
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: bug/double-opt-in-triggered-despite-being-disabled-in-settings

</Details>


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [x] Yes
- [ ] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Review by jeffpaul — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with the `smoke-testing` branch, it works as expected, similar to the fix-specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.7.1
- Theme: Twenty Twenty-Four 1.3
- WooCommerce - 9.5.1
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>
