### PR TITLE
Make the form field visibility dependent on the WordPress "Include?" settings instead of the Mailchimp settings.

### LINKED ISSUE #34: Address and Phone Number Form Fields Missing on Frontend
### Describe the bug

The address and phone number form fields are configured and available in the backend settings, but they do not appear on the frontend.

**Expected Behavior:**
Upon enabling the address and phone number fields in the Mailchimp setup under Merge Fields Included, these fields should be visible and accessible on the frontend.

### Steps to Reproduce

1. Navigate to the WordPress Admin Dashboard.
2. Go to "Settings" and select "Mailchimp Setup" from the dropdown menu.
3. Inside the Mailchimp setup, locate and click on "Merge Fields Included".
4. Enable the fields for "Address" and "Phone Number".
5. Save the settings 
6. Visit the frontend of the website.
7. Observe that the address and phone number fields do not appear on the subscription form.

### Screenshots, screen recording, code snippet

https://github.com/mailchimp/wordpress/assets/67687255/9d1bb25a-b3b5-49a5-bbc2-60d2ac1f2e2c

### Environment information

**Testing Environment** 

WordPress: 6.5.4
Theme: Twenty Twenty-Four 1.1
PHP: 8.1.23
Web Server: Nginx 1.20.2
Browser: Chrome 
OS: macOS Ventura 13.3 

### WordPress information

_No response_

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iamdharmesh**
### Description of the Change
This PR updates the existing behavior of how form fields are displayed on the form. Currently, form fields are shown based on a combination of settings from both Mailchimp and WordPress. If a form field is marked as hidden in Mailchimp, it does not appear on the form, while a visible field can be included in the form based on the settings on the WordPress side.

This PR updates this behavior so that form field visibility is determined solely by the **"Include?"** option in the WordPress settings, regardless of the Mailchimp settings.

When a new list is set up, hidden fields in Mailchimp will have their **"Include?"** setting turned off (hidden) by default. Additionally, this PR includes an upgrade script to ensure that forms with hidden fields based on Mailchimp settings do not accidentally start displaying after the update.

Closes #34

### How to test the Change
1. Mark a few form fields as hidden in Mailchimp.  
2. Go to the **Mailchimp settings** page in wp-admin, log in to your Mailchimp account, and select an audience list.  
3. Verify that hidden fields have their **"Include?"** setting turned off (checkbox unchecked) by default.  
4. Enable the **"Include?"** option for hidden fields and save the settings.  
5. Go to the front end and verify that the form field is now visible.  
6. Submit the form with values and confirm that:  
   - The form submits successfully.  
   - The submitted details are correctly reflected in the Mailchimp contact.
   
#### Backward Compatibility  
1. For existing users on the `trunk` branch:  
   - Set up the plugin and form.  
   - Verify that form fields are hidden based on Mailchimp settings.  
2. Update to this PR branch and change the plugin version to **1.7.0** in [`mailchimp.php`](https://github.com/mailchimp/wordpress/blob/develop/mailchimp.php#L68) by replacing the line with:  
   ```php
   define( 'MCSF_VER', '1.7.0' );
   ```  
3. Visit the settings page and ensure that all hidden fields have **"Include?"** turned off and are not visible on the front end.  

### Credits

Props @qasumitbagthariya @dkotter @jeffpaul @MaxwellGarceau @iamdharmesh 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/mailchimp/wordpress/blob/develop/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: mailchimp.php [hunk 1]
```diff
@@ -683,9 +683,15 @@ function mailchimp_sf_get_merge_vars( $list_id, $new_list ) {
 	update_option( 'mc_merge_vars', $mv['merge_fields'] );
 	foreach ( $mv['merge_fields'] as $mv_var ) {
 		$opt = 'mc_mv_' . $mv_var['tag'];
-		// turn them all on by default
 		if ( $new_list ) {
-			update_option( $opt, 'on' );
+			$public = isset( $mv_var['public'] ) ? $mv_var['public'] : false;
```
Comment (dkotter) [inline mailchimp.php:687]:
```suggestion
			$public = $mv_var['public'] ?? false;
```

**Review by dkotter — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
### QA Update  ✅

-------------

I have verified this PR in the `fix/34` branch, which has been fixed and is functioning as intended.

I tested the following on this branch:
- Follow the test steps provided in the PR description.
- Backward Compatibility

https://github.com/user-attachments/assets/7e6ae4e1-7929-4bd4-af1b-d41f40cffc23


https://github.com/user-attachments/assets/db2d329b-b289-48ae-aa5e-21a862a0466b



**Testing Environment** 

<Details>

- WordPress: 6.7.2
- Theme: Storefront 4.6.1
- Theme: Twenty Twenty-Four 1.3
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: fix/34

</Details>


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready forUAT
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR
------------------------------------------------

**Review by qasumitbagthariya — APPROVED** [review]

**Comment by qasumitbagthariya** [comment]
Regression / Smoke Test Report  ✅ 
-------

Tested with the `smoke-testing` branch, it works as expected, similar to the fix-specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.7.2
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.3
- PHP: 8.2.23
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>


Next Step- Ready to Merge 🚀
